/**
 * Configuración del sitio METGO Paine.
 * Al clonar la plantilla, este es el ÚNICO archivo a editar para identidad + módulos + seed.
 */
export default {
  sitio: 'paine',
  productName: 'METGO',
  siteLabel: 'Paine',
  tagline: 'Torres del Paine · Circuitos W y O',
  region: 'Torres del Paine',
  versionLabel: 'v2.1 · METGO Glaciares',
  documentTitle: 'METGO Paine — Glaciares · Torres del Paine',
  documentDescription:
    'METGO Paine — clima, nieve y criósfera en Torres del Paine, Patagonia chilena.',
  center: { lat: -50.96, lon: -73.05 },
  theme: {
    primary: '#22d3ee',
    primaryHover: '#06b6d4',
    accent: '#38bdf8',
    accentLight: '#7dd3fc',
  },
  modules: {
    meteo: true,
    precipitacion: true,
    lugares: true,
    aire: false,
    operaciones: false,
  },
  storagePrefix: 'metgo_paine',
  copy: {
    headerTitle: 'Sistema de monitoreo',
  },
  /** Seed UI / fallback si la API cae (ids numéricos para vistas legacy). */
  stations: [
    {
      id: 1,
      slug: 'base_torres',
      nombre: 'Base Torres',
      circuito: 'W',
      altitud: 900,
      lat: -50.9417,
      lon: -72.9667,
      descripcion: 'Mirador Base Torres - Punto más emblemático del circuito',
      dificultad: 'Alta',
      icono: 'Mountain',
    },
    {
      id: 2,
      slug: 'glaciar_grey',
      nombre: 'Glaciar Grey',
      circuito: 'W',
      altitud: 50,
      lat: -51.0,
      lon: -73.23,
      descripcion: 'Refugio Glaciar Grey - Zona occidental con vista al glaciar',
      dificultad: 'Media',
      icono: 'Snowflake',
    },
    {
      id: 3,
      slug: 'valle_frances',
      nombre: 'Valle del Francés',
      circuito: 'W',
      altitud: 300,
      lat: -50.9667,
      lon: -73.0833,
      descripcion: 'Mirador Valle del Francés - Centro del circuito',
      dificultad: 'Media-Alta',
      icono: 'Trees',
    },
    {
      id: 4,
      slug: 'paine_grande',
      nombre: 'Refugio Paine Grande',
      circuito: 'O',
      altitud: 50,
      lat: -50.95,
      lon: -73.1167,
      descripcion: 'Refugio principal - Lago Pehoé',
      dificultad: 'Baja',
      icono: 'Home',
    },
    {
      id: 5,
      slug: 'campamento_italiano',
      nombre: 'Campamento Italiano',
      circuito: 'W',
      altitud: 120,
      lat: -50.9583,
      lon: -73.0667,
      descripcion: 'Campamento base Valle del Francés',
      dificultad: 'Media',
      icono: 'Tent',
    },
    {
      id: 6,
      slug: 'los_cuernos',
      nombre: 'Los Cuernos',
      circuito: 'O',
      altitud: 200,
      lat: -50.975,
      lon: -73.05,
      descripcion: 'Refugio Los Cuernos',
      dificultad: 'Media',
      icono: 'Mountain',
    },
  ],
}
